### ISSUE TITLE
Error Initializing context ROCm 5.3.0

### ISSUE THREAD

**Issue by tictooc** [StreamHPC/openmm-hip-old#3]
HIP is recognized as a platform, but any attempt to run benchmarks or tests with HIP will fail.  The results are the same whether running via conda, or building the plugin locally, on a machine running ROCm 5.3.0.

```
$ python -m openmm.testInstallation
There are 4 Platforms available:

1 Reference - Successfully computed forces
2 HIP - Error computing forces with HIP platform
3 CPU - Successfully computed forces
4 OpenCL - Successfully computed forces

HIP platform error: Error initializing Context: hipErrorNotSupported (801) at /home/conda/feedstock_root/build_artifacts/openmm-hip_1648191410518/work/openmm-hip/platforms/hip/src/HipContext.cpp:196
```

The same error, `HIP platform error: Error initializing Context: hipErrorNotSupported (801)`, occurs on all the HIP tests.

ROCm 5.2.3 works without issue.

**Comment by ex-rzr** [comment]
Thanks for the report! I'll investigate the issue.

**Comment by ex-rzr** [comment]
Fixed: https://github.com/StreamHPC/openmm-hip/commit/e261dc055779dcc93d465c0bd89d9d734c79bb9a

This change causes the issue: https://github.com/ROCm-Developer-Tools/hipamd/commit/e8f938b60fdd93ab7411bb5fc53d7da03124c5d9

I've also updated the conda package. It doesn't require a custom package of openmm anymore, instead it depends on 8.0.0rc (openmm_rc) so the command is slightly different:
```
conda create -n openmm-env -c streamhpc -c conda-forge/label/openmm_rc -c conda-forge openmm-hip
```

**Comment by tictooc** [comment]
The benchmark, HIP tests, and local tests now run without issue on ROCm 5.3.0.
